### ISSUE TITLE
Estatus cuenta bancaria

### ISSUE THREAD

**Issue by jcramirez79** [NetVaIT/delphi-standard#2]
Agregar el estatus a la cuenta bancaria y cuenta bancaria roles

CREATE TABLE CuentasBancariasEstatus (
      IdCuentaBancariaEstatus int IDENTITY(1,1) NOT NULL Primary Key,
      Identificador varchar (5) NOT NULL,
      Descripcion varchar(50) NOT NULL
);
ALTER TABLE CuentasBancarias 
ADD IdCuentaBancariaEstatus int NULL;

ALTER TABLE CuentasBancarias 
ADD CONSTRAINT FK_CuentasBancarias_CuentasBancariasEstatus 
FOREIGN KEY (IdCuentaBancariaEstatus) REFERENCES CuentasBancariasEstatus (IdCuentaBancariaEstatus);

ALTER TABLE PersonasRolesCuentasBancarias 
ADD IdCuentaBancariaEstatus int NULL;

ALTER TABLE PersonasRolesCuentasBancarias 
ADD CONSTRAINT FK_FK_CuentasBancarias_CuentasBancariasEstatus_CuentasBancariasEstatus 
FOREIGN KEY (IdCuentaBancariaEstatus) REFERENCES CuentasBancariasEstatus (IdCuentaBancariaEstatus);

SET IDENTITY_INSERT [dbo].[CuentasBancariasEstatus] ON
INSERT [dbo].[CuentasBancariasEstatus]([IdCuentaBancariaEstatus], [Identificador], [Descripcion]) VALUES (1, N'A', N'Activa')
INSERT [dbo].[CuentasBancariasEstatus]([IdCuentaBancariaEstatus], [Identificador], [Descripcion]) VALUES (2, N'I', N'Inactiva')
INSERT [dbo].[CuentasBancariasEstatus]([IdCuentaBancariaEstatus], [Identificador], [Descripcion]) VALUES (3, N'B', N'Baja')
SET IDENTITY_INSERT [dbo].[CuentasBancariasEstatus] OFF

**Comment by jhuante** [comment]
Ya esta listo el cambio ... 
![image](https://cloud.githubusercontent.com/assets/4365813/9552975/aae07f30-4d81-11e5-977a-74ada3925d9b.png)

se ajusto el SQL ya que es una tabla fija

CREATE TABLE CuentasBancariasEstatus (
      IdCuentaBancariaEstatus int NOT NULL Primary Key,
      Identificador varchar (5) NOT NULL,
      Descripcion varchar(50) NOT NULL
);

INSERT [dbo].[CuentasBancariasEstatus]([IdCuentaBancariaEstatus], [Identificador], [Descripcion]) VALUES (1, N'A', N'Activa')
INSERT [dbo].[CuentasBancariasEstatus]([IdCuentaBancariaEstatus], [Identificador], [Descripcion]) VALUES (2, N'I', N'Inactiva')
INSERT [dbo].[CuentasBancariasEstatus]([IdCuentaBancariaEstatus], [Identificador], [Descripcion]) VALUES (3, N'B', N'Baja')

ALTER TABLE CuentasBancarias ADD IdCuentaBancariaEstatus int NULL;
UPDATE CuentasBancarias SET IdCuentaBancariaEstatus = 1;
ALTER TABLE CuentasBancarias ALTER COLUMN IdCuentaBancariaEstatus int NOT NULL;

ALTER TABLE CuentasBancarias
ADD CONSTRAINT FK_CuentasBancarias_CuentasBancariasEstatus
FOREIGN KEY (IdCuentaBancariaEstatus) REFERENCES CuentasBancariasEstatus (IdCuentaBancariaEstatus);

ALTER TABLE PersonasRolesCuentasBancarias ADD IdCuentaBancariaEstatus int NOT NULL;
UPDATE PersonasRolesCuentasBancarias SET IdCuentaBancariaEstatus = 1
ALTER TABLE PersonasRolesCuentasBancarias ALTER COLUMN  IdCuentaBancariaEstatus int NOT NULL;

ALTER TABLE PersonasRolesCuentasBancarias
ADD CONSTRAINT FK_FK_CuentasBancarias_CuentasBancariasEstatus_CuentasBancariasEstatus
FOREIGN KEY (IdCuentaBancariaEstatus) REFERENCES CuentasBancariasEstatus (IdCuentaBancariaEstatus);
